<?php

namespace MSergeev\Packages\Icar\Tables;

use MSergeev\Core\Entity;
use MSergeev\Core\Lib\DataManager;
use MSergeev\Core\Lib\TableHelper;

class CarBrandTable extends DataManager {
	public static function getTableName() {
		return 'ms_icar_car_brand';
	}
	public static function getTableTitle() {
		return 'Бренды автомобилей';
	}
	public static function getTableLinks() {
		return array(
			'ID' => array(
				'ms_icar_my_car' => 'CAR_BRAND_ID',
				'ms_icar_car_model' => 'CAR_BRAND_ID',
			)
		);
	}
	public static function getMap() {
		return array(
			new Entity\IntegerField('ID',array(
				'primary' => true,
				'autocomplete' => true,
				'title' => 'ID Бренда'
			)),
			TableHelper::activeField(),
			TableHelper::sortField(),
			new Entity\StringField('NAME',array(
				'required' => true,
				'title' => 'Имя бренда'
			)),
			new Entity\StringField('CODE',array(
				'required' => true,
				'run' => array(
					'function' => "\\MSergeev\\Core\\Lib\\Tools::generateCode",
					'column' => 'NAME'
				),
				'unique' => true,
				'title' => 'Код бренда'
			))
		);
	}

	public static function getArrayDefaultValues()
	{
		return array(
			array(
				'ID'=>1,
				'NAME'=>'AC Cars',
				'CODE'=>'ac_cars'
			),
			array(
				'ID'=>2,
				'NAME'=>'Acura',
				'CODE'=>'acura'
			),
			array(
				'ID'=>3,
				'NAME'=>'Alfa Romeo',
				'CODE'=>'alfa_romeo'
			),
			array(
				'ID'=>4,
				'NAME'=>'Alpina',
				'CODE'=>'alpina'
			),
			array(
				'ID'=>5,
				'NAME'=>'Aston Martin',
				'CODE'=>'aston_martin'
			),
			array(
				'ID'=>6,
				'NAME'=>'Audi',
				'CODE'=>'audi'
			),
			array(
				'ID'=>7,
				'NAME'=>'Bentley',
				'CODE'=>'bentley'
			),
			array(
				'ID'=>8,
				'NAME'=>'BMW',
				'CODE'=>'bmw'
			),
			array(
				'ID'=>9,
				'NAME'=>'Bogdan',
				'CODE'=>'bogdan'
			),
			array(
				'ID'=>10,
				'NAME'=>'Brilliance',
				'CODE'=>'brilliance'
			),
			array(
				'ID'=>11,
				'NAME'=>'Bugatti',
				'CODE'=>'bugatti'
			),
			array(
				'ID'=>12,
				'NAME'=>'Buick',
				'CODE'=>'buick'
			),
			array(
				'ID'=>13,
				'NAME'=>'BYD',
				'CODE'=>'byd'
			),
			array(
				'ID'=>14,
				'NAME'=>'Cadillac',
				'CODE'=>'cadillac'
			),
			array(
				'ID'=>15,
				'NAME'=>'Changan',
				'CODE'=>'changan'
			),
			array(
				'ID'=>16,
				'NAME'=>'Chery',
				'CODE'=>'chery'
			),
			array(
				'ID'=>17,
				'NAME'=>'Chevrolet',
				'CODE'=>'chevrolet'
			),
			array(
				'ID'=>18,
				'NAME'=>'Chrysler',
				'CODE'=>'chrysler'
			),
			array(
				'ID'=>19,
				'NAME'=>'Citroen',
				'CODE'=>'citroen'
			),
			array(
				'ID'=>20,
				'NAME'=>'Dacia',
				'CODE'=>'dacia'
			),
			array(
				'ID'=>21,
				'NAME'=>'Daewoo',
				'CODE'=>'daewoo'
			),
			array(
				'ID'=>22,
				'NAME'=>'Daf',
				'CODE'=>'daf'
			),
			array(
				'ID'=>23,
				'NAME'=>'Daihatsu',
				'CODE'=>'daihatsu'
			),
			array(
				'ID'=>24,
				'NAME'=>'Datsun',
				'CODE'=>'datsun'
			),
			array(
				'ID'=>25,
				'NAME'=>'Derways',
				'CODE'=>'derways'
			),
			array(
				'ID'=>26,
				'NAME'=>'Dodge',
				'CODE'=>'dodge'
			),
			array(
				'ID'=>27,
				'NAME'=>'FAW',
				'CODE'=>'faw'
			),
			array(
				'ID'=>28,
				'NAME'=>'Ferrari',
				'CODE'=>'ferrari'
			),
			array(
				'ID'=>29,
				'NAME'=>'FIAT',
				'CODE'=>'fiat'
			),
			array(
				'ID'=>30,
				'NAME'=>'Ford',
				'CODE'=>'ford'
			),
			array(
				'ID'=>31,
				'NAME'=>'Geely',
				'CODE'=>'geely'
			),
			array(
				'ID'=>32,
				'NAME'=>'GMC',
				'CODE'=>'gmc'
			),
			array(
				'ID'=>33,
				'NAME'=>'Great Wall',
				'CODE'=>'great_wall'
			),
			array(
				'ID'=>34,
				'NAME'=>'Haima',
				'CODE'=>'haima'
			),
			array(
				'ID'=>35,
				'NAME'=>'Honda',
				'CODE'=>'honda'
			),
			array(
				'ID'=>36,
				'NAME'=>'Hummer',
				'CODE'=>'hummer'
			),
			array(
				'ID'=>37,
				'NAME'=>'Hyundai',
				'CODE'=>'hyundai'
			),
			array(
				'ID'=>38,
				'NAME'=>'Infiniti',
				'CODE'=>'infiniti'
			),
			array(
				'ID'=>39,
				'NAME'=>'Iran Khodro',
				'CODE'=>'iran_khodro'
			),
			array(
				'ID'=>40,
				'NAME'=>'Isuzu',
				'CODE'=>'isuzu'
			),
			array(
				'ID'=>41,
				'NAME'=>'IVECO',
				'CODE'=>'iveco'
			),
			array(
				'ID'=>42,
				'NAME'=>'Jaguar',
				'CODE'=>'jaguar'
			),
			array(
				'ID'=>43,
				'NAME'=>'Jeep',
				'CODE'=>'jeep'
			),
			array(
				'ID'=>106,
				'NAME'=>'JMC',
				'CODE'=>'jmc'
			),
			array(
				'ID'=>44,
				'NAME'=>'Kia',
				'CODE'=>'kia'
			),
			array(
				'ID'=>45,
				'NAME'=>'Komatsu',
				'CODE'=>'komatsu'
			),
			array(
				'ID'=>46,
				'NAME'=>'Lamborghini',
				'CODE'=>'lamborghini'
			),
			array(
				'ID'=>47,
				'NAME'=>'Lancia',
				'CODE'=>'lancia'
			),
			array(
				'ID'=>48,
				'NAME'=>'Land Rover',
				'CODE'=>'land_rover'
			),
			array(
				'ID'=>49,
				'NAME'=>'Lexus',
				'CODE'=>'lexus'
			),
			array(
				'ID'=>50,
				'NAME'=>'Lifan',
				'CODE'=>'lifan'
			),
			array(
				'ID'=>51,
				'NAME'=>'Lincoln',
				'CODE'=>'lincoln'
			),
			array(
				'ID'=>52,
				'NAME'=>'Lotus',
				'CODE'=>'lotus'
			),
			array(
				'ID'=>53,
				'NAME'=>'LUXGEN',
				'CODE'=>'luxgen'
			),
			array(
				'ID'=>54,
				'NAME'=>'MAN',
				'CODE'=>'man'
			),
			array(
				'ID'=>55,
				'NAME'=>'Maserati',
				'CODE'=>'maserati'
			),
			array(
				'ID'=>56,
				'NAME'=>'Maybach',
				'CODE'=>'maybach'
			),
			array(
				'ID'=>57,
				'NAME'=>'Mazda',
				'CODE'=>'mazda'
			),
			array(
				'ID'=>58,
				'NAME'=>'Mercedes-Benz',
				'CODE'=>'mercedes_benz'
			),
			array(
				'ID'=>59,
				'NAME'=>'Mercury',
				'CODE'=>'mercury'
			),
			array(
				'ID'=>60,
				'NAME'=>'MG',
				'CODE'=>'mg'
			),
			array(
				'ID'=>61,
				'NAME'=>'Microcar',
				'CODE'=>'microcar'
			),
			array(
				'ID'=>62,
				'NAME'=>'MINI',
				'CODE'=>'mini'
			),
			array(
				'ID'=>63,
				'NAME'=>'Mitsubishi',
				'CODE'=>'mitsubishi'
			),
			array(
				'ID'=>64,
				'NAME'=>'Morgan',
				'CODE'=>'morgan'
			),
			array(
				'ID'=>65,
				'NAME'=>'Nino',
				'CODE'=>'nino'
			),
			array(
				'ID'=>66,
				'NAME'=>'Nissan',
				'CODE'=>'nissan'
			),
			array(
				'ID'=>67,
				'NAME'=>'Opel',
				'CODE'=>'opel'
			),
			array(
				'ID'=>68,
				'NAME'=>'Peugeot',
				'CODE'=>'peugeot'
			),
			array(
				'ID'=>69,
				'NAME'=>'Plymouth',
				'CODE'=>'plymouth'
			),
			array(
				'ID'=>70,
				'NAME'=>'Pontiac',
				'CODE'=>'pontiac'
			),
			array(
				'ID'=>71,
				'NAME'=>'Porsche',
				'CODE'=>'porsche'
			),
			array(
				'ID'=>72,
				'NAME'=>'Proton',
				'CODE'=>'proton'
			),
			array(
				'ID'=>73,
				'NAME'=>'Renault',
				'CODE'=>'renault'
			),
			array(
				'ID'=>74,
				'NAME'=>'Rolls-Royce',
				'CODE'=>'rolls_royce'
			),
			array(
				'ID'=>75,
				'NAME'=>'Rover',
				'CODE'=>'rover'
			),
			array(
				'ID'=>76,
				'NAME'=>'Saab',
				'CODE'=>'saab'
			),
			array(
				'ID'=>77,
				'NAME'=>'Saturn',
				'CODE'=>'saturn'
			),
			array(
				'ID'=>78,
				'NAME'=>'Scania',
				'CODE'=>'scania'
			),
			array(
				'ID'=>79,
				'NAME'=>'Scion',
				'CODE'=>'scion'
			),
			array(
				'ID'=>80,
				'NAME'=>'SEAT',
				'CODE'=>'seat'
			),
			array(
				'ID'=>81,
				'NAME'=>'Skoda',
				'CODE'=>'skoda'
			),
			array(
				'ID'=>82,
				'NAME'=>'Smart',
				'CODE'=>'smart'
			),
			array(
				'ID'=>83,
				'NAME'=>'SsangYong',
				'CODE'=>'ssangyong'
			),
			array(
				'ID'=>84,
				'NAME'=>'Subaru',
				'CODE'=>'subaru'
			),
			array(
				'ID'=>85,
				'NAME'=>'Suzuki',
				'CODE'=>'suzuki'
			),
			array(
				'ID'=>86,
				'NAME'=>'Tata',
				'CODE'=>'tata'
			),
			array(
				'ID'=>87,
				'NAME'=>'Toyota',
				'CODE'=>'toyota'
			),
			array(
				'ID'=>88,
				'NAME'=>'TVR',
				'CODE'=>'tvr'
			),
			array(
				'ID'=>89,
				'NAME'=>'Vauxhall',
				'CODE'=>'vauxhall'
			),
			array(
				'ID'=>90,
				'NAME'=>'Volkswagen',
				'CODE'=>'volkswagen'
			),
			array(
				'ID'=>91,
				'NAME'=>'Volvo',
				'CODE'=>'volvo'
			),
			array(
				'ID'=>92,
				'NAME'=>'Vortex',
				'CODE'=>'vortex'
			),
			array(
				'ID'=>93,
				'NAME'=>'ZX',
				'CODE'=>'zx'
			),
			array(
				'ID'=>94,
				'NAME'=>'ВАЗ',
				'CODE'=>'vaz'
			),
			array(
				'ID'=>95,
				'NAME'=>'ВИС',
				'CODE'=>'vis'
			),
			array(
				'ID'=>96,
				'NAME'=>'ГАЗ',
				'CODE'=>'gaz'
			),
			array(
				'ID'=>97,
				'NAME'=>'ЗАЗ',
				'CODE'=>'zaz'
			),
			array(
				'ID'=>98,
				'NAME'=>'ЗИЛ',
				'CODE'=>'zil'
			),
			array(
				'ID'=>99,
				'NAME'=>'ИЖ',
				'CODE'=>'ij'
			),
			array(
				'ID'=>100,
				'NAME'=>'КАМАЗ',
				'CODE'=>'kamaz'
			),
			array(
				'ID'=>101,
				'NAME'=>'ЛУАЗ',
				'CODE'=>'luaz'
			),
			array(
				'ID'=>102,
				'NAME'=>'Москвич',
				'CODE'=>'moskvich'
			),
			array(
				'ID'=>103,
				'NAME'=>'СеАЗ',
				'CODE'=>'seaz'
			),
			array(
				'ID'=>104,
				'NAME'=>'ТагАЗ',
				'CODE'=>'tagaz'
			),
			array(
				'ID'=>105,
				'NAME'=>'УАЗ',
				'CODE'=>'uaz'
			)
		);
	}
}