<?php
/**
 * Локализация раздела "Мои автомобили"
 *
 * @package MSergeev\Packages\Icar
 * @subpackage Loc
 * @author Mikhail Sergeev <msergeev06@gmail.com>
 * @copyright 2016 Mikhail Sergeev
 */

return array(
	'mycars_my_cars'            => 'Мои машины',
	'mycars_add_car'            => 'Добавить автомобиль',
	'mycars_auto_in_garage'     => 'Автомобили в вашем гараже',
	'mycars_default'            => 'по-умолчанию',
	'mycars_y'                  => 'г.',
	'mycars_car_number'         => "Гос.&nbsp;номер",
	'mycars_vin'                => 'VIN',
	'mycars_body_type'          => 'Тип кузова',
	'mycars_gearbox'            => 'Коробка передач',
	'mycars_engine_capacity'    => 'Объем двигателя',
	'mycars_l'                  => 'л.',
	'mycars_auto_cost'          => 'Стоимость автомобиля',
	'mycars_rub'                => 'руб.',
	'mycars_credit'             => 'Кредит',
	'mycars_yes'                => 'Да',
	'mycars_no'                 => 'Нет',
	'mycars_interval_ts'        => 'Интервал ТО',
	'mycars_km'                 => 'км.',
	'mycars_date_end_osago'     => 'Дата окончания ОСАГО',
	'mycars_date_end_gto'       => 'Дата окончания ГТО',
	'mycars_total_costs'        => 'Всего расходов',
	'mycars_average_fuel'       => 'Средний расход топлива',
	'mycars_l_100km'            => 'л./100км.',
	'mycars_spent_fuel'         => 'Израсходованно топлива',
	'mycars_current_mileage'    => 'Текущий пробег',
	'mycars_description'        => 'Дополнительное описание',
	'mycars_construction'       => 'В разработке',
	'mycars_car_photo'          => 'Фотографии автомобиля',
	'mycars_default_car'        => 'Автомобиль по-умолчанию',
	'mycars_adding_car'         => 'Добавление автомобиля',
	'mycars_alert_ts_green'     => 'Обратите внимание! Скоро необходимо будет проходить плановое ТО на автомобиле "#CAR_NAME#"! Осталось проехать #KM# км',
	'mycars_alert_ts_yellow'    => 'Внимание! В ближайшее время необходимо пройти плановое ТО на автомобиле "#CAR_NAME#"! Осталось проехать #KM# км',
	'mycars_alert_ts_red'       => 'ВНИМАНИЕ! Необходимо в срочном порядке пройти плановое ТО на автомобиле "#CAR_NAME#"!',
	'mycars_alert_osago_green'  => 'Заканчивается срок действия полиса ОСАГО у автомобиля "#CAR_NAME#". Рекомендуем позаботится о продлении заранее. Осталось #DAY_NUM# #DAY_TEXT#',
	'mycars_alert_osago_yellow' => 'Внимание! Скоро закончится срок действия полиса ОСАГО у автомобиля "#CAR_NAME#". Необходимо продлить полис! Осталось #DAY_NUM# #DAY_TEXT#',
	'mycars_alert_osago_red'    => 'ВНИМАНИЕ! Сегодня заканчиватся срок действия полиса ОСАГО у автомобиля "#CAR_NAME#". Необходимо СРОЧНО продлить полис!',
	'mycars_alert_osago_red2'   => 'ВНИМАНИЕ! Закончился срок действия полиса ОСАГО у автомобиля "#CAR_NAME#". Необходимо СРОЧНО продлить полис!',
	'mycars_alert_gto_green'    => 'Подходит дата очередного ГТО у автомобиля "#CAR_NAME#". Подготовьте автомобиль к осмотру. Осталось #DAY_NUM# #DAY_TEXT#',
	'mycars_alert_gto_yellow'   => 'Внимание! Скоро подойдет дата очередного ГТО у автомобиля "#CAR_NAME#". Последняя возможность подготовить автомобиль к осмотру! Осталось #DAY_NUM# #DAY_TEXT#',
	'mycars_alert_gto_red'      => 'ВНИМАНИЕ! Сегодня последний день действия ГТО на автомобиле "#CAR_NAME#". Необходимо СРОЧНО пройти ГТО!',
	'mycars_alert_gto_red2'     => 'ВНИМАНИЕ! Необходимо СРОЧНО пройти ГТО на автомобиле "#CAR_NAME#". Езда без ГТО может привести к штрафу и лишению прав. Необходимо СРОЧНО пройти ГТО!',
	'mycars_car_name'           => 'Название авто',
	'mycars_car_active'         => 'Автомобиль активен',
	'mycars_sort'               => 'Сортировка',
	'mycars_car_brand'          => 'Марка авто',
	'mycars_car_model'          => 'Модель',
	'mycars_car_year'           => 'Год выпуска',
	'mycars_num_and_lat'        => 'Цифры и латинские буквы',
	'mycars_litra'              => 'литра',
	'mycars_auto_cost_buy'      => 'Стоимость при покупке',
	'mycars_mileage_buy'        => 'Пробег при покупке',
	'mycars_car_credit'         => 'Автомобиль в кредит',
	'mycars_car_credit_cost'    => 'Сумма кредита',
	'mycars_set_notice'         => 'Настроить напоминание',
	'mycars_car_older'          => 'Автомобиль настолько старый? Не верю!',
	'mycars_car_add_success'    => 'Автомобиль успешно добавлен',
	'mycars_car_no_delete'      => 'Данный автомобиль удалить невозможно, так как существуют данные, ссылающиеся на него.',
	'mycars_car_delete'         => 'Удаление автомобиля',
	'mycars_car_confirm_delete' => 'Я подтверждаю, что хочу удалить автомобиль "#CAR_NAME#", c номером "#CAR_NUMBER#"!',
	'mycars_button_car_delete'  => 'Удалить автомобиль',
	'mycars_car_del_success'    => 'Автомобиль успешно удален',
	'mycars_car_del_error'      => 'При удалении возникла ошибка. Автомобиль не был удален',
	'mycars_car_edit'           => 'Редактирование автомобиля',
	'mycars_select_model'       => 'Выберите модель',
	'mycars_add_model'          => 'Добавьте модель',
	'mycars_change_save_success'=> 'Изменения успешно сохранены'
);